### ISSUE TITLE
Step 4 inaccessable

### ISSUE THREAD

**Issue by RRastronaut** [SciStarter-Team/SciStarter-Bugs#10]
After completing the course and attaining 100%, the next steps is still inaccessable.

**Comment by SciStarter** [comment]
Hi, can you tell me which course you're having trouble with?

**Comment by libgrrl52** [comment]
Hi, I am unable to get to the certificate granting part after completing all courses and obtaining all three badges

**Comment by SciStarter** [comment]
Libgrrl52, our records show that you have been granted all three badges and that the pages are fully unlocked for you. If you like, I can provide you with download links via email, or you should be able to find them on badgr.com as well.

Edit: You can also find your badges collected on your SciStarter dashboard, at https://scistarter.org/dashboard/profile
