### ISSUE TITLE
Project Squirrel not progressing

### ISSUE THREAD

**Issue by k-stor** [SciStarter-Team/SciStarter-Bugs#14]
Hi there. I can't progress to Step 4 because the page is not updating to reflect that I've submitted data for Project Squirrel (I've tried several times). Is there something I can do to fix this? Thanks!

**Comment by SciStarter** [comment]
Several people were effected by a slowdown in processing Project Squirrel entries over the weekend. We think that everybody who should has now gotten credit, so I'm going to close this issue, but if you still have trouble feel free to re-open it, and I'll help you out.
