### ISSUE TITLE
Not getting Training Badge & screen lockup

### ISSUE THREAD

**Issue by snhoier** [SciStarter-Team/SciStarter-Bugs#15]
After completion of rest !t end of lesson, about 20 hrs ago, I didn't get any badge. My training is stuck at step #3, saying "You are almost there".
The lesson I have completed was "Teaching in higher Eduction with Citizen Science."
I was using Samsung 23 Ultra. I had received 2 badges a few days before my "screen lockup.".
Thx for helping.
Sally Hoier, snhoier@gmail.com 
![Screenshot_20240811_192254_Gallery](https://github.com/user-attachments/assets/38a30493-9111-4191-a24e-c5dc19aefdd0)

**Comment by SciStarter** [comment]
I believe you have now received your badge, and the training page should reflect that if you visit it again.
