### ISSUE TITLE
SSA widget interface pagation and project number errors

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#18]
Discovered at the time time as issue #17 & #16 

# Observations
## 11 Nov 2024
1. On when searching  "bat" and "bats" both for Australia and South Australia (SA) via SSA again, 8 projects showed up on the first visible page that said "1-8 of 10" 
2.  The number for page 1 is blue when selected, whereas I could have expected black for the one selected as Google searching does. 
3. When clicking page 2 in the top nav, she got "9-16 of 10" showing at the top, which is erroneous and the same 8 projects continued to show without changes. 

## 18 Nov 2024
Numbers still do not accurately reflect the correct number of projects
<img width="797" alt="image" src="https://github.com/user-attachments/assets/4631b060-a5a2-4b06-9858-e62c9d526ee3">

# Recommended actions for RM once DA fixes bugs
 - [ ] Conduct searches listed in #17 and see if issue persists

**Comment by ElMounRo** [comment]
Since no bat projects are showing in my search, I searched for "koala" and got 10 results.
The numbering was fine, though: page 1 read "1-8 of 10" and page 2 read "9-10 of 10".

**Comment by JessieLOliver** [comment]
Note quite ready to close. The pagination issue looks fixed now for the SciStarter Australia page, but when I search bats I got the same results. Do I need to clear cookies or something? 

- The first project in the top right "Mallee CMA region" is relevant for the state of Victoria in Australia. 
- "Bats Count! Bat Cam Emergence Count" is a Connecticut project from the looks of it, it should not be showing. Can you identify why this is occurring for this project? Note it's "Presented by: CitSci.org"
- "Dark Sky Meter" has the tag bats, which is likely why it's coming up. The app does not document any biodiversity as afar as  I can tell and bats need very specific audio detectors, so please remove bats from this project's tags so it doesn't come up any more.  

<img width="443" alt="image" src="https://github.com/user-attachments/assets/05130826-cb55-418a-ac7c-f952bb7037f0">

**Comment by SciStarter** [comment]
Search for "bat" instead of "bats" to get more. That "s" overspecifies the search somewhat. If you want the two searches to be equivalent, I can work on that, but please open it as a new issue, as it's unrelated to the main topic of this one.

Bats Count is marked as a global project, rather than being specific to Connecticut.

Dark Sky Meter is explicitly tagged "bats"

**Comment by JessieLOliver** [comment]
Right but can the metadata of those projects be correct to be CT-focused and without bat as a tag since neither aspect of metadata is relevant for the respective projects? Look at the project descriptions, and it's pretty clear the metadata isn't correct.

**Comment by JessieLOliver** [comment]
Additionally, I am actually realising the page information still doesn't seem intuitive to me. Can you explain what the numbers #-# of # are actually meant to represent? I thought they were pages, but note this one still lists 3 as the end number even though they are all on the same page?

**Comment by SciStarter** [comment]
Dark Sky Meter should not be tagged with "bats," and I'll remove that tag.

Bats Count Cam is correctly identified as a worldwide participation project. Australians are entirely capable of participating and welcome to do so.

As to the pagination numbers, those refer to the projects. Page 1 is projects 1-8 (if there are at least 8 projects in the result). As is common for such displays, the page number display uses colors to identify the current page and page range, while the item display shows you which projects your viewing and the total.

**Comment by JessieLOliver** [comment]
- So why is it that searching "bat" versus "bats" doesn't return equivalent results? For example, when searching "bat" fewer results came up (e.g. "Flying Fox Monitoring Project" https://github.com/SciStarter-Team/SciStarter-Bugs/issues/16#issuecomment-2494818973 didn't come up with "bats",  noting that a "flying fox" is a type of giant fruit-eating Australian bat). 
- We may need to add some search hot tips to support people on how to get the best search results if there are such caveats. People did get quite confused when doing state vs national searches as well, in terms of what they expected would show.
- Searching "bat" also brought up "Identificar e Monitorar Fósseis no Geoparque Corumbataí/SP" https://scistarter.org/exchange/35/7978/project.html and I while I can only partly read it, it doesn't seem geographically relevant or to have and terms ending in b-a-t that should have pulled it up. 
-  Bats Count Cam - Good call. it wasn't immediately obvious to me it was an online project from looking at citsci.org, but I can see a bit more of a clear potential to participation from the partner website: https://portal.ct.gov/deep/wildlife/live-bats-count-bat-cam
- It would be useful to create a set of icons to indicate things like whether a project is global, a specific location (e.g. a map pinpoint icon) online, outside, in the lab etc. for the thumbnails and overview pages so people can quickly scan searches and understand such info quickly.

**Comment by SciStarter** [comment]
I have updated the query again. See #29 for more info.
