### ISSUE TITLE
SSA exchange links don't consistently show via thumbnail

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#20]
# Observation 
## 07 Nov 2024
When doing a keyword search via the SciStarter Australia widget and clicking on thumbnails to project overviews, the type of URL showing is inconsistent. 
- Example 1: When clicking *Victoria's bushfire emergency: Biodiversity response and recovery* people are taken to the overview page with a generic link still showing rather than an exchange link
<img width="710" alt="image" src="https://github.com/user-attachments/assets/5fa692a9-e036-4e1a-9dc3-c9539fd431f6">

- Example 2: When clicking on *The Giant Eucalypts Project* the participant was taken to a page that showed the exchange URL: https://scistarter.org/exchange/35/9424/project.html) 

## 18 Nov 2024 
I attempted to replicate this issue and the same generic link listed in Example 1 is now showing for both projects now

# Confirmation needed
-[ ] DA can you please confirm this is an intentional change and functioning as expected?

**Comment by SciStarter** [comment]
The behavior you describe under the 18 Nov 2024 has been the behavior all along. It would have been a very significant change to the code to make it behave otherwise, so I'm confident in saying there has been no change.
