### ISSUE TITLE
Help with getting credit for completing Foundations of Science online training

### ISSUE THREAD

**Issue by estheranneyoon** [SciStarter-Team/SciStarter-Bugs#3]
Hi! Just completed the Foundations of Science online training, but when I close class and go back to https://verizon.scistarter.org/ and log in, Step 3 is grayed out and I'm unable to move forward. (Looking like I did not complete) Step 2.

<img width="949" alt="Foundations of Science Tutorial" src="https://user-images.githubusercontent.com/93797226/140581001-4c658a75-98fe-4c16-a445-dcc3439293c0.png">

**Comment by SciStarter** [comment]
You needed to be logged in to SciStarter before doing the training in order for your account to be credited with the training, per the instructions.

**Comment by estheranneyoon** [comment]
I was logged in.🙁
Followed the instructions step by step.

<http://www.verizon.com>

Esther Yoon Smith, MBA

Sr. Trainer
Learning and Development
Verizon Consumer Group


M 808 557 0888
3375 Koapaka Street, Suite B220
Honolulu, Hawaii 96819

*Clifton Top 5 Strengths*

*Connectedness *| *Relator *| *Learner *| *Positivity* | *Developer*

**Comment by SciStarter** [comment]
Okay, sorry about that. You should be able to progress now.

**Comment by estheranneyoon** [comment]
No worries, thanks!

<http://www.verizon.com>

Esther Yoon Smith, MBA

Sr. Trainer
Learning and Development
Verizon Consumer Group


M 808 557 0888
3375 Koapaka Street, Suite B220
Honolulu, Hawaii 96819

*Clifton Top 5 Strengths*

*Connectedness *| *Relator *| *Learner *| *Positivity* | *Developer*

**Comment by jlastraglio** [comment]
Hello, I am experiencing the same issue, logged in as well

![image](https://user-images.githubusercontent.com/93995217/140944517-5f4a93a6-236e-4d5a-9a74-0e8d3f17437b.png)

**Comment by SciStarter** [comment]
You should now be able to progress as well.
