### ISSUE TITLE
Make fields not filled out on project overview pages invisble?

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#37]
To help records look more complete, is there a way to only show fields that hold data?

At present, the same fields seem to show for all overview pages, but many of the fields are blank, which really gives a sense of incompleteness, which, in my view, isn't a great look for anybody (even if true), so instead of having a default of showing all fields (empty or not) can only fields with content be displayed on overview pages?

**Comment by SciStarter** [comment]
The fields are now only displayed if they contain something to display.
