### ISSUE TITLE
Help with getting credit for completing foundations of science training

### ISSUE THREAD

**Issue by jlastraglio** [SciStarter-Team/SciStarter-Bugs#4]
Hello, I have completed the training twice but it will not allow me to move to step 3. I am logged in as welll

![image](https://user-images.githubusercontent.com/93995217/140950455-695fa946-a400-4ff1-984f-206f7dfd504b.png)

**Comment by SciStarter** [comment]
We haven't been able to locate your SciStarter account based on your github username, so we can't confirm anything about your current status. Are you still having this problem?

**Comment by lanvargas** [comment]
I am having the same problem as the person above.  I have completed the training and it won't let me move on.  When I worked on stallcatchers, it didn't record my activity.

**Comment by SciStarter** [comment]
Please tell us what your SciStarter username is so we can check your account.

**Comment by lanvargas** [comment]
MrsV

Thank you,
 
 



On Fri, 28 Jan 2022 11:38:56 -0800, SciStarterOwner ***@***.***> wrote:
 
 

Please tell us what your SciStarter username is so we can check your account.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SciStarter** [comment]
You should be able to proceed now.
