### ISSUE TITLE
Duplicate project in SSG: “Echidna-CSI” and “EchidnaCSI”

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#41]
“Echidna-CSI” (https://scistarter.org/echidna-csi) is squelched in SSA but both “Echidna-CSI” and “EchidnaCSI” come up when searching in SSG due to title variation. Please squelch “Echidna-CSI” (https://scistarter.org/echidna-csi)

**Comment by SciStarter** [comment]
Done
