### ISSUE TITLE
SSG and SSA search unexpectedly differently, incl an SSA project not showing in SSG 

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#43]
### Retrieved in SSA, but not SSG 
_Chequered Copper (Lucia limbaria) butterfly monitoring_ when searched by both project title and "butterfly"

**SSA URL**: https://scistarter.org/exchange/35/9311/project.html 
Last updated SSA page: Wed Jul 24 07:34:17 2024 +0000 *(don’t know who edited it, but given that it’s recent and anomalous, I do wonder who)*
**SSG URL**: Unknown; Not pulled up on SSG
Last updated SSG page: Unknown

### Unexpected search differences across systems
-Searched SSG for “butterfly monitoring” and 4 projects came up but not this one, whether signed in as staff or public (not logged in)
- Searched in SSA by the project title and “butterfly monitoring” and 60 and 65 projects came up in signed in and not, respectively, with most being unrelated to butterflies, similar to how we had with water projects. 
- If the SSA result is because I included the word monitoring, why doesn't this happen for SSG as well?
- I would have expected the system to filter by consistent mechanisms with the exception of geographically relevant parameters. 

### Side note on project geography change
Could you also please change the geography on this project while looking at it?
*Geographic change needed*: From Australia to SA only for this project

**Comment by SciStarter** [comment]
FYI the scistarter.org address for that project is https://scistarter.org/chequered-copper-lucia-limbaria-butterfly-monitori

The main scistarter.org search is frankly a step back from the one used on SSG, and I'm in the process of bringing it up to the same standard. In the meantime, finding differences is not surprising and not a cause for concern unless SSA is negatively impacted. Actually, even after, finding differences is not a cause for concern, as they will be operating with different parameters.

I have updated the geometry for the project to South Australia.
