### ISSUE TITLE
Truncate the image credit field for the overview

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#46]
When on the exchange, searching as public (i.e., not signed in as staff), and only ticking "Australia" then going to page 2, the URL being included in the credit field for the _Post bushfire regeneration and repopulation_ project (https://scistarter.org/exchange/35/5022/project.html) is too long, so when projects are searched it stretches across two both columns and there heaps of white space on one side: 
<img width="627" alt="image" src="https://github.com/user-attachments/assets/4bcc1061-c283-44db-90d2-fc83e8fef043" />

I suspect that this issue is also what's causing the "Feral Scan" project to have a blank space next to it at the bottom of the same page, but please confirm this. 
<img width="632" alt="image" src="https://github.com/user-attachments/assets/1cc2106d-db11-43e1-a590-2e57127975a0" />

The next project, at the top of the next page (3) "[The National Waterbug Blitz](https://scistarter.org/exchange/35/4990/project.html)" seems to have a typical thumbnail size.

<img width="596" alt="image" src="https://github.com/user-attachments/assets/8d03aabe-6f95-46ac-92f8-018992330332" />

**Comment by SciStarter** [comment]
I've set the image credit to have a constrained size, with the full value visible when you hover your mouse over it. You are probably correct about why the Feral Scan project had a blank next to it, but the effect wasn't visible when I checked, even before fixing the credit length.

The waterbug blitz project does have an unusual aspect ratio for their image. There's not much to be done about that.
