### ISSUE TITLE
Truncate long descriptions for SSA like done with SSG 

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#47]
SSG description truncation example for an OZ project (https://scistarter.org/great-barrier-reef-recovery-at-magnetic-island): 
<img width="944" alt="image" src="https://github.com/user-attachments/assets/b8db9d64-2028-4ee4-bd97-2e731dba5c69" />

See un-truncated via the exchange URL: https://scistarter.org/exchange/35/176/project.html

**Comment by SciStarter** [comment]
Okay, done.
