### ISSUE TITLE
Completed Foundation Of Citizen Science Course But Not Reflected.

### ISSUE THREAD

**Issue by yufa91** [SciStarter-Team/SciStarter-Bugs#5]
Completed Foundation Of Citizen Science Course But Not Reflected,

**Comment by SciStarter** [comment]
We have no way of identifying your SciStarter account based on this report. Would you be willing to provide your SciStarter username so we can check on your status?

**Comment by yufa91** [comment]
Hi

My user id should be yufa91.

On Fri, Jan 14, 2022 at 10:36 PM SciStarterOwner ***@***.***>
wrote:

> We have no way of identifying your SciStarter account based on this
> report. Would you be willing to provide your SciStarter username so we can
> check on your status?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SciStarter-2DTeam_SciStarter-2DBugs_issues_5-23issuecomment-2D1013301140&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=cMAcYxbIUbVL70RIHNAArSgAra4cKjg11npr5sGB_uY&s=4SuWIF2GR7yHAUADZBO2rJdn940p9mlF_J2QpyU73O0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AXJXTPBZHGIKUSDS3WES7LLUWBJXZANCNFSM5L67BOJQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=cMAcYxbIUbVL70RIHNAArSgAra4cKjg11npr5sGB_uY&s=dpGBbhEusYT4-KDzSPvhN17pZ7_u0ACawY6GgRIcw9U&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=cMAcYxbIUbVL70RIHNAArSgAra4cKjg11npr5sGB_uY&s=i10i-_Ln0ACjXdz80994F4RSBtI9SdQY06WDXRNyJYc&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=cMAcYxbIUbVL70RIHNAArSgAra4cKjg11npr5sGB_uY&s=VBwMGHYZW1uuSH3IjNtBdvQfak1l9kLN0vCjuVlzkwQ&e=>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Regards:
*Yusuf H.*
*POS Omni Retail*
*Verizon India*

**Comment by SciStarter** [comment]
I'm sorry, but no such account exists. Please add a screenshot of your logged-in SciStarter home page so we can figure his out.

**Comment by yufa91** [comment]
Hi PFB Screen  Shot.

[image: image.png]
![image](https://user-images.githubusercontent.com/97745340/149794001-83fb49fc-d1bc-4b45-92e5-a6a988eece15.png)


On Mon, Jan 17, 2022 at 5:37 PM SciStarterOwner ***@***.***>
wrote:

> I'm sorry, but no such account exists. Please add a screenshot of your
> logged-in SciStarter home page so we can figure his out.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SciStarter-2DTeam_SciStarter-2DBugs_issues_5-23issuecomment-2D1014450946&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=qXPP4jZpUBKtsd7B91F8g1PYz5IjpkTcAJ-ses_ZO28&s=fBASjsyEgbKE6--nb-kcEy02kVeBBYS4C7TOY7n0Yq8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AXJXTPCUX65FCV2C244QU5LUWQBAVANCNFSM5L67BOJQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=qXPP4jZpUBKtsd7B91F8g1PYz5IjpkTcAJ-ses_ZO28&s=_sjQKnFWVEj0WvjiV6qaxnfbC-pSm70GN3Kk8RCI_Jg&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=qXPP4jZpUBKtsd7B91F8g1PYz5IjpkTcAJ-ses_ZO28&s=T5dTIa7e_LeDXaHFaXakFLsKxDa1E_B1iRvubctHB4Y&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=8jJIOL7_4-YdfrPR3vH4-atEjZh-pOC6pXz34L3njsQUYsH1C28ZHfz3mlXum-nh&m=qXPP4jZpUBKtsd7B91F8g1PYz5IjpkTcAJ-ses_ZO28&s=CoApPQ91i8p3EZn_qZkwWRGyd7G6Y2lM18us1uHkXiY&e=>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Regards:
*Yusuf H.*
*POS Omni Retail*
*Verizon India*

**Comment by SciStarter** [comment]
To add a screenshot, copy and paste or drag and drop the image into the text box.

**Comment by SciStarter** [comment]
Okay, you should be able to proceed now.
