### ISSUE TITLE
finished the tutorial. 

### ISSUE THREAD

**Issue by gitamooney** [SciStarter-Team/SciStarter-Bugs#6]
https://scistarter.org/training?utm_campaign=UM33 - Step 3 still grayed out.  Refreshed the page too

Even got a 100% on the tutorial

**Comment by SciStarter** [comment]
Please let me know your SciStarter username so I can check your account state

**Comment by MHay29** [comment]
Step 3 is still grayed after completing and passing the tutorial. https://media.scistarter.org/foundations/index.html#/lessons/VGTkgQ_Po63-plah4U6jRTUGFmzSw7KM

**Comment by SciStarter** [comment]
Please tell me your SciStarter username so I can check you account state.

**Comment by DDesylvia01** [comment]
Hi, I completed the Foundations of Citizen Science but Step 3 has not opened up for me. Please help!

**Comment by SciStarter** [comment]
I will be happy to help, but I need to be able to identify your SciStarter account, so please let me know what your SciStarter username is here.

**Comment by DDesylvia01** [comment]
Thank you! My username is ddesylvia31

**Comment by SciStarter** [comment]
Okay, you should be able to proceed now.
