### ISSUE TITLE
cant progress beyond step 3 of training even though I've participated in squirrel count and stall catchers.

### ISSUE THREAD

**Issue by KendraBober** [SciStarter-Team/SciStarter-Bugs#7]
Please help; I'm doing traiing for work and can't play game all day!

**Comment by SciStarter** [comment]
Happy to help. Please tell me your SciStarter username.

**Comment by KendraBober** [comment]
BHLKendraBober@gmail.com

**Comment by KendraBober** [comment]
(thanks)

**Comment by SciStarter** [comment]
You should be able to proceed now. I've deleted the comment containing your email to protect your privacy.

**Comment by KendraBober** [comment]
Tried - closed tab and re-opened and navigated to training page but it's still greyed out beyond #3

**Comment by SciStarter** [comment]
Hmm. When I masquerade as you and view the page, I see step 4 available. Maybe try holding down shift and reloading the page, to make sure you have everything up to date.

**Comment by KendraBober** [comment]
Just tried that and tried closing tab again, opening, logging out and back in and it's still grey

**Comment by SciStarter** [comment]
Okay, please check again.

**Comment by KendraBober** [comment]
thanks!

**Comment by SciStarter** [comment]
You're welcome. Good luck!
