### ISSUE TITLE
Part 3 of Citizen science

### ISSUE THREAD

**Issue by jadabean** [SciStarter-Team/SciStarter-Bugs#8]
My part 3 is grayed out and will not let me continue although I have completed the first two tasks.

![image](https://user-images.githubusercontent.com/106356559/170601063-beb7bf50-491d-4524-a4ac-5aad35b70451.png)

**Comment by SciStarter** [comment]
What is the username (also known as handle, I'm not asking for your email) for your account? Once I have that I'll be able to set things right for you.

**Comment by ashleyHodges** [comment]
I also completed the tutorial and passed the quiz, but part 3 is greyed out as shown above. 
My username is ashleyHodges (I believe that is correct, I don't see a username in my SciStarter profile)

**Comment by SciStarter** [comment]
I'm sorry, I can't find your account. Are you sure that's the correct username? When you're logged in to SciStarter, your  username should be visible in the dark blue header area at the top.

**Comment by ashleyHodges** [comment]
![image](https://user-images.githubusercontent.com/106389140/170711280-f3d8ad40-a167-4028-9684-4686d87fa058.png)

**Comment by ashleyHodges** [comment]
Is it Ashley ?

**Comment by ashleyHodges** [comment]
or just ashley.hodges ?

**Comment by SciStarter** [comment]
Found it, and you should be able to proceed now.
