### ISSUE TITLE
Contribution is not Saving

### ISSUE THREAD

**Issue by ashleyHodges** [SciStarter-Team/SciStarter-Bugs#9]
I've submitted a contribution 3 times & it is not reflecting in my Dashboard. 
Steps to Reproduce:

1. Visit my Dashboard
2. Locate 'The Great Sunflower project' & Select 'Participate'
3. Select 'Continue to The Great Sunflower Project'
4. Enter details
5. Select 'Submit'
6. Return to Dashboard
7. View no additional increase in count of contributions
![image](https://user-images.githubusercontent.com/106389140/171190424-2eba3cae-2c3a-41c9-ac3e-f8d71e368eb3.png)
![image](https://user-images.githubusercontent.com/106389140/171190629-9be16062-a872-4c0e-bc8b-21cc06feac5a.png)
![image](https://user-images.githubusercontent.com/106389140/171190649-cd2f56c2-ffb8-4c97-928e-7e294e7bba28.png)

**Comment by SciStarter** [comment]
It appears that your Great Sunflower Project contributions have now arrived in our system.
